### ISSUE TITLE
作者大佬好。

### ISSUE THREAD

**Issue by Demonsword27** [CodeTips/WeChatPlugin-iOS#5]
刚刚入了逆向的坑，早上刚刚在玩，就被封了，所以在查防封的操作，我看到你是hook了ClientCheckMgr这个类的几个检测方法和动态修改了id，趁着号解封这个期间，想问问 你这样做是否真的有效，我拿的是最新的6.7.2的版本在玩😂，一会解封了试试

**Comment by kevieYu** [comment]
怎么样好使吗

**Comment by CodeTips** [comment]
我自己试了试还可以，但是最好不要用新号。新号好像会严格一些。这些方法是我找的网上一些微信VIP版本 反编译出来的。我手机是越狱的，我用的插件形式。一直正常使用。

**Comment by Demonsword27** [comment]
@CodeTips  6.7.1用了很久 基本没事，6.7.3新的包还没试过。我到时候试试  用的人多了感觉这个可能马上会被补漏。😂

**Comment by MessageDream** [comment]
6.7.3会被封
